### ISSUE TITLE
crash on server start

### ISSUE THREAD

**Issue by adamsonich** [HxCKDMS/HxCCore#27]
[23:07:49] [Server thread/ERROR] [FML/]: The following problems were captured during this phase
[23:07:50] [Server thread/ERROR] [FML/]: Caught exception from HxCCore
java.lang.NullPointerException
        at HxCKDMS.HxCCore.HxCCore.getNewVer(HxCCore.java:258) ~[HxCCore.class:?]
        at HxCKDMS.HxCCore.HxCCore.lambda$serverStart$1(HxCCore.java:148) ~[HxCCore.class:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_73]
        at HxCKDMS.HxCCore.HxCCore.serverStart(HxCCore.java:146) ~[HxCCore.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_73]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_73]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_73]
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_73]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_73]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]

**Comment by DrZed** [comment]
Well then, uhm, disable it in config.... (Version Check)

**Comment by DrZed** [comment]
I'll have to check it later

**Comment by DrZed** [comment]
It should be fixed, I have someone using my mod on server and no issues
